module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    borderWidth: {
      DEFAULT: '1px',
      0: '0',
      1: '1px',
      2: '2px',
      3: '3px',
      4: '4px',
      6: '6px',
      8: '8px',
    },
    colors: {
      white: '#FFFFFF',
      BLUE: '#187498',
      BLUE50: '#4f46e5',
      BLUE100: '#17B9B4',
      BLUEDARK: '#45378B',
      Purp: '#581c87',
      Purp100: '#45378B',
      Purp200: '#695CAD',
      Purp300: '#453783',
      Purp400: '#382F68',
      Purp500: '#322A8A',
      GREEN: '#36AE7C',
      GREEN100: '#17C1BC',
      YELLOW: '#E0A719',
      SKY: '#17C1BC',
      RED: '#EB5353',
      GRAY: '#CCCCCC',
      GRAYLIGHT: '#EAE9E9',
      GRAY50: '#B0B0B0',
      GRAY100: '#F5F5F5',
      GRAY200: '#DDDDDD',
      GRAY300: '#7F7F7F',
      GRAY400: '#686767',
    },

    // backgroundImage: (theme) => ({
    //   'fifth-bg': "url('/assest/images/images/Fifth-bg.png')",
    //   'branding-outlines': "url('/assest/images/images/branding-outlines.png')",
    //   'circle-center': "url('/assest/images/images/circle-center.png')",
    //   // mobile: "url('./assets/images/mobile.png')",
    // }),
    gradientColorStops: (theme) => ({
      primary: '#45378B',
      secondary: '#1D1C90',
    }),
    extend: {
      backgroundImage: {
        jordan: "url('/assest/images/jordan.jpg')",
        kuwait: "url('/assest/images/kuwait.jpg')",
        saudi: "url('/assest/images/saudi.jpg')",
        egypt: "url('/assest/images/egypt.jpg')",
        'fifth-bg': "url('/assest/images/images/Fifth-bg.png')",
        'branding-outlines':
          "url('/assest/images/images/branding-outlines.png')",
        'circle-center': "url('/assest/images/images/circle-center.png')",
        // mobile: "url('./assets/images/mobile.png')",
      },
      fontFamily: {
        TSExtra: ['TsExtrabold'],
        TSSemi: ['TsSemibold'],
        TSbold: ['Tsbold'],
        TSmedium: ['TsMed'],
        TSthin: ['TsThin'],
        TSlight: ['TsLight'],
        NTbold: ['NotoBold'],
        NTsemibold: ['NotoSemiBold'],
        NTmedium: ['NotoMedium'],
        NTregular: ['NotoRegular'],
      },
    },
  },
  plugins: [require('tailwindcss-rtl')],
}
